# Use the latest PHP image with Apache
FROM php:8.3.2-apache
WORKDIR /var/www/html

# Install mysqli extension
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Copy application files
COPY ./web /var/www/html/
