services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
  
volumes:
  mysql_data:
    # Define volume for persisting MySQL data
